# Generated by Django 6.0.3 on 2026-05-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0002_alter_recipe_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
