# Generated by Django 6.0.3 on 2026-05-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0004_drop_recipe_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="estimated_duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
