# Generated by Django 6.0.3 on 2026-05-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wip", "0015_simplify_result_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="auto_complete_at",
            field=models.DateTimeField(
                blank=True,
                help_text="模擬機台預定完成時間 — start 進 running 時設為 now + 隨機 3~5 秒。前端輪巡用 (auto_complete_at - now) 顯示倒數，到點自動完成；與 completed_at（實際完成時間戳）刻意區分。",
                null=True,
            ),
        ),
    ]
